name: Frontend CD

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./starter/frontend

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: CI=true npm test

  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: 'movie-catalog'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Build Docker image
        run:  docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 -t $IMAGE_NAME:${{ github.sha }}  .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Deploy to Prod
        run: echo "Deploying to production"
